package mock

import (
	"fmt"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"unicode"
	"unicode/utf8"
)

// callStack returns an array of strings containing the file and line number
// of each stack frame leading from the current test to the assert call that
// failed.
//
// Copied from: https://github.com/stretchr/testify/blob/5ac6528bffc1ed7557980c3c563caf8308568446/assert/assertions.go#L214
func callStack() []string {
	// TODO(rz): everywhere this is used check if we show callstack
	var pc uintptr
	var ok bool
	var file string
	var line int
	var name string

	callers := make([]string, 0, 10)
	for i := 0; ; i++ {
		pc, file, line, ok = runtime.Caller(i)
		if !ok {
			// The breaks below failed to terminate the loop,
			// and we ran off the end of the call stack.
			break
		}

		// This is a huge edge case,
		// but it will panic if this is the case, see #180
		if file == "<autogenerated>" {
			break
		}

		f := runtime.FuncForPC(pc)
		if f == nil {
			break
		}
		name = f.Name()

		// The testing.tRunner is the standard library function that calls
		// tests. Subtests are called directly by tRunner, without going
		// through the Test/Benchmark/Example function that contains the t.Run
		// calls, so with subtests we should break when we hit tRunner, without
		// adding it to the list of callers.
		if name == "testing.tRunner" {
			break
		}

		parts := strings.Split(file, "/")
		file = parts[len(parts)-1]
		if len(parts) > 1 {
			path, _ := filepath.Abs(file)
			callers = append(callers, fmt.Sprintf("%s:%d", path, line))
		}

		// Drop the package.
		segments := strings.Split(name, ".")
		name = segments[len(segments)-1]
		if isTest(name, "Test") ||
			isTest(name, "Benchmark") ||
			isTest(name, "Example") {
			break
		}
	}

	return callers
}

// formatCall formats information about a method call. To show argument values
// set values to true.
func formatCall(method string, args Arguments, values bool, leftPad int) string {
	// TODO(rz): this method is not needed.
	var out []string
	pad := strings.Repeat("\t", leftPad) // TODO(rz): dont use tabs
	out = append(out, fmt.Sprintf("%s%s(%s)", pad, method, args.String(-1)))
	if values && len(args) > 0 {
		for idx, arg := range args {
			out = append(out, fmt.Sprintf("%s\t%d: %#v", pad, idx, arg))
		}
	}
	return strings.Join(out, "\n")
}

func formatMethod(method string, args, rets Arguments) string {
	// TODO(rz):
	// TODO(rz): test this.
	var out []string
	argsStr := args.String(-1)
	retsStr := rets.String(-1)
	if len(rets) > 1 {
		retsStr = "(" + retsStr + ")" // TODO(rz): test this.
	}
	if len(rets) > 0 { // TODO(rz): test this.
		retsStr = " " + retsStr
	}
	out = append(out, fmt.Sprintf("%s(%s)%s", method, argsStr, retsStr))
	return strings.Join(out, "\n")
}

func formatArgs(args Arguments) string {
	if len(args) == 0 {
		return ""
	}
	var out []string
	for idx, arg := range args {
		out = append(out, fmt.Sprintf("%d: %s", idx, dumper.Any(arg)))
	}
	return strings.Join(out, "\n")
}

// formatStack formats call stack.
func formatStack(stack []string, padLeft int) string {
	// TODO(rz): I don't think we need it when we use notice messages.
	if len(stack) == 0 {
		return ""
	}
	var out []string
	pad := strings.Repeat("\t", padLeft)
	for _, line := range stack {
		out = append(out, pad+line)
	}
	return strings.Join(out, "\n")
}

// formatDiff formats diff lines.
func formatDiff(diff []string, padLeft int) string {
	var out string
	pad := strings.Repeat("\t", padLeft)
	for _, line := range diff {
		out += pad + line + "\n"
	}
	return out
}

// Stolen from the `go test` tool.
//
// isTest tells whether name looks like a test (or benchmark, according to
// prefix). It is a Test (say) if there is a character after "Test" that is
// not a lower-case letter. We don't want TesticularCancer.
func isTest(name, prefix string) bool {
	// TODO(rz): rename this - it has nothing to do with "Test".
	if !strings.HasPrefix(name, prefix) {
		return false
	}
	if len(name) == len(prefix) { // "Test" is ok.
		return true
	}
	r, _ := utf8.DecodeRuneInString(name[len(prefix):])
	return !unicode.IsLower(r)
}

// methodName returns method name.
//
// Copied from:	https://github.com/emicklei/go-restful/blob/1959514610d2124125005c8a6a3962d6cca32a16/route_builder.go#L375
//
// Example:
//
//	ptr := &types.TPtr{}
//	met := reflect.ValueOf(ptr.AAA)
//	methodName(met)
func methodName(met reflect.Value) string {
	fun := runtime.FuncForPC(met.Pointer())
	name := fun.Name()
	tokenized := strings.Split(name, ".")
	last := tokenized[len(tokenized)-1]
	last = strings.TrimSuffix(last, ")·fm") // < Go 1.5
	last = strings.TrimSuffix(last, ")-fm") // Go 1.5
	last = strings.TrimSuffix(last, "·fm")  // < Go 1.5
	last = strings.TrimSuffix(last, "-fm")  // Go 1.5
	return last
}

// twoColumns aligns the text in second column to the longest string in the
// first column. Stores the result in the first column.
//
// Example:
//
//	aaa 111
//	bb  222
//	c   333
func twoColumns(col1, col2 []string) {
	var longest int
	for _, s := range col1 {
		if len(s) > longest {
			longest = len(s)
		}
	}
	for i, s := range col2 {
		ind := strings.Repeat(" ", longest-len(col1[i]))
		col1[i] = fmt.Sprintf("%s %s%s", col1[i], ind, s)
	}
}
